### PR TITLE
594

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some documentation

**Description**

### CODE REVIEW

**Comment by sylvainpelissier** [comment]
Should we close this one ?

**Comment by trufae** [comment]
Is the ci now using latest r2-594?

**Comment by sylvainpelissier** [comment]
No it fails for linux20: https://github.com/radareorg/r2yara/pull/32

**Comment by sylvainpelissier** [comment]
In #32 the error is not in the testsuite it is: 
```/usr/bin/ld: /home/runner/.local/share/radare2/prefix/lib/libyara.a(la-threading.o): in function `yr_thread_storage_get_value':
threading.c:(.text+0xf7): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status```

**Comment by trufae** [comment]
Looks like missing -lpthread

**Pull request closed without merging**
